server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300


#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#feign:
#  client:
#    config:
#      default: #所有@@FeignClient 标注的feign客户端都是用这个配置
#        connectTimeout: 500
#        readTimeout: 5000
#        retryer: com.atguigu.gmall.common.retry.MyRetryer #自定义的feign重试器